name: CI
on:
  push:
    branches: 
      - '*'
      - '*/*'
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.2 

      - name: Install dependencies
        run: npm install --force

      - name: Build of code 
        run: npm run build

      - name: Run unit tests
        run: npm run test

